"""add work_orders indexes

Revision ID: b163f2c35a7d
Revises: 
Create Date: 2026-08-16 13:34:34.963355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b163f2c35a7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plants_name'), ['name'], unique=True)

    op.create_table('transporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pan_card', sa.String(length=20), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('contact', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transporters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transporters_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mines_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_mines_plant_id'), ['plant_id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lorry_number', sa.String(length=50), nullable=False),
    sa.Column('transporter_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('total_freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tds_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mines_name', sa.String(length=200), nullable=True),
    sa.Column('mine_id', sa.Integer(), nullable=True),
    sa.Column('mines_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['transporter_id'], ['transporters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'lorry_number', name='uq_trip_date_lorry')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index('ix_trip_date', ['date'], unique=False)
        batch_op.create_index('ix_trip_plant', ['plant_id'], unique=False)
        batch_op.create_index('ix_trip_transporter', ['transporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_transporter_id'), ['transporter_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_number', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('lorry_number', sa.String(length=50), nullable=False),
    sa.Column('mine_id', sa.Integer(), nullable=True),
    sa.Column('tds', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ddtds', sa.Date(), nullable=True),
    sa.Column('account_advance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mines_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('plant_qty', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_freight', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('loading', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_advance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shortage', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('short_amt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('munsiyana', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rtgs', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_account_name'), ['account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_lorry_number'), ['lorry_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_mine_id'), ['mine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_work_order_number'), ['work_order_number'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_trip_id'), ['trip_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('beneficiary_name', sa.String(length=200), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_trip_id'), ['trip_id'], unique=False)

    op.create_table('petrol_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('petrol_stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_petrol_stations_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petrol_stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_petrol_stations_work_order_id'))

    op.drop_table('petrol_stations')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_trip_id'))

    op.drop_table('payments')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_trip_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_work_order_number'))
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))
        batch_op.drop_index(batch_op.f('ix_work_orders_mine_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_lorry_number'))
        batch_op.drop_index(batch_op.f('ix_work_orders_date'))
        batch_op.drop_index(batch_op.f('ix_work_orders_account_name'))

    op.drop_table('work_orders')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_transporter_id'))
        batch_op.drop_index(batch_op.f('ix_trips_plant_id'))
        batch_op.drop_index(batch_op.f('ix_trips_mine_id'))
        batch_op.drop_index(batch_op.f('ix_trips_date'))
        batch_op.drop_index('ix_trip_transporter')
        batch_op.drop_index('ix_trip_plant')
        batch_op.drop_index('ix_trip_date')

    op.drop_table('trips')
    with op.batch_alter_table('mines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mines_plant_id'))
        batch_op.drop_index(batch_op.f('ix_mines_name'))

    op.drop_table('mines')
    op.drop_table('audit_logs')
    op.drop_table('users')
    with op.batch_alter_table('transporters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transporters_name'))

    op.drop_table('transporters')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plants_name'))

    op.drop_table('plants')
    # ### end Alembic commands ###
